name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies 
      run: npm install
    - name: Run the unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "karajov15"

  build-ui-tests:
    runs-on: ubuntu-latest
    needs: build-unit-tests

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies 
      run: npm install
    - name: Install PlayWright
      run: npx playwright install
    - name: Start the application
      run: npm run start &
    - name: Run the UI tests
      run: npm run test:ui

  deploy:
    runs-on: ubuntu-latest
    needs: build-ui-tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
